disabled_rules:
- line_length
- trailing_whitespace
- orphaned_doc_comment
- nesting
- type_body_length
- parameter
- force_cast
- large_tuple
- identifier_name

included:
excluded:
- Pods
- MoMo/Sources/AppDelegate.swift
- MoMo/Sources/SceneDelegate.swift
- MoMo/Resources/Constants/APIConstants.swift

file_length:
  warning: 1000
  error: 1200
